### PR TITLE
fix: Support CORS for image

### PR DESCRIPTION
**Pull request by dhyegocalota**
# Issue
https://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported

### CODE REVIEW

**Comment by hsluoyz** [comment]
This PR has causes serious bug: Chrome latest version won't show any images

My env: 

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
```

Please revert this PR immediately.

**Comment by x5engine** [comment]
this is a bug, you can't download or generate the urldata

**Comment by x5engine** [comment]
it doesnt fix the crossorigin

> It's worth noting that setting image.crossOrigin = 'Anonymous' won't help once the image has been loaded. But if a reload is an option you can go for something like: document.querySelectorAll('img').forEach(image => { image.crossOrigin = 'Anonymous'; image.src += ' '; })

**Comment by fosteman** [comment]
Struggling with image export as well too. Any solution so far ?

**Comment by hsluoyz** [comment]
Solution is here: https://github.com/tbolis/react-sketch/issues/95

**Comment by fosteman** [comment]
> Solution is here: #95

This is a circular link to this post. 
Do I need to update the module to have the problem fixed @hsluoyz ?

**Comment by hsluoyz** [comment]
@fosteman I used my only fork to fix it: https://github.com/hsluoyz/react-sketch/  , also available in npmjs

**Pull request merged**
