### PR TITLE
add support for React v16.0 and improve SketchField CodeBase

### PR DESCRIPTION
**Pull request by fjogeleit**
- add Support for React v16.0
- update dependencies
- fix Tests and add es6 Support for PhantomJS via karma-es6-shime
- update SketchField CodeBase

### CODE REVIEW

**Comment by danilowoz** [comment]
Nice job @tbolis and @fjogeleit!
Please merge it! I really need this!

**Comment by fjogeleit** [comment]
hi @danilowoz , thanks a lot. If you already want to use this version you can use the builded version from my gists: https://gist.github.com/fjogeleit/cb7ed3b636b2207c756ae72c51cb428b

**Comment by danilowoz** [comment]
@tbolis could you please publish this new version in the npm? :)

**Comment by tbolis** [comment]
it is already in the npm use npm version 0.4.1 and let me know if you are ok

**Comment by danilowoz** [comment]
That's work now! Thanks

**Pull request merged**
